FROM coinpit/nodejs:v8
COPY scripts/automation.js package.json package-lock.json scripts/conf.js dist/
COPY build build/
RUN apt-get update && apt-get install -y git && cd dist && npm install --only=production
