FROM coinpit/nodejs:v8
COPY scripts/automation.js package.json scripts/conf.js dist/
COPY contracts contracts/
RUN apt-get update && apt-get install -y git && cd dist && npm install --only=production
