FROM coinpit/nodejs:v8
COPY dist1 ./dist1
RUN apt-get update && apt-get install git -y && cd dist && npm install -production && useradd leverj
EXPOSE 8888
USER leverj
CMD node dist1/src-admin/server/index.js
